import { registerEnumType } from "@nestjs/graphql";

export enum ParcelExportFields {
  uid = "Parcel UID",
  clientCompanyName = "Client",
  clientPhoneNumber = "Client Phone",
  clientAddress = "Client Address",
  clientCity = "Client City",
  clientCountry = "Client Country",
  clientStorage = "Client Storage Option",
  receiverName = "Receiver",
  receiverPhoneNumber = "Receiver Phone",
  receiverAddress = "Receiver Address",
  receiverCity = "Receiver City",
  receiverCountry = "Receiver Country",
  returnedTo = "Returned To",
  returnedPhone = "Return Phone",
  returnedAdress = "Return Address",
  returnedCity = "Return City",
  returnedCountry = "Return Country",
  country = "Country",
  aging = "Parcel Aging",
  deliveryDate = "Parcel Delivery Date",
  returnDate = "Parcel Return Date",
  lastOpsUpdate = "Parcel Last OPS Update",
  reconcilDate = "Parcel Reconcil Date",
  reconcilAgent = "Parcel Reconcil Agent",
  lastUpdatePapserDate = "Last Update Papser Date",
  lastUpdatePapser = "Last Update Papser",
  lastUpdatePapserPhone = "Last Update Papser Phone",
  collectionByCashierDate = "Parcel Collection By Cashier Date",
  lastOpsUpdateName = "Parcel Last OPS Update Name",
  lastOpsUpdatePhone = "Parcel Last OPS Update Phone",
  slots = "Slots",
  size = "Parcel Size",
  attempts = "Parcel Attemps",
  attemptsReal = "Parcel Attemps Real",
  creation = "Parcel Creation Date",
  scheduledAt = "Scheduled Date",
  pickupDate = "Parcel Pickup Date",
  amountToCollect = "Parcel Amount To Collect",
  status = "Parcel Status",
  lastDriverName = "Parcel Last Driver Name",
  lastDriverPhone = "Parcel Last Driver Phone",
  lastDriverUid = "Parcel Last Driver UID",
  vehicleType = "Vehicle Type",
  lastConveyorName = "Parcel Last Conveyor Name",
  lastConveyorPhone = "Parcel Last Conveyor Phone",
  lastConveyorUid = "Parcel Last Conveyor UID",
  lastPartner = "Parcel Last Partner",
  orderUid = "Order UID",
  orderNumberOfParcels = "Number Of Parcel In Order",
  orderCreation = "Order Creation Date",
  orderSize = "Order Size",
  orderAmounToCollect = "Order Amount Collect",
  orderAmountCollected = "Order Amount Collected",
  orderStatus = "Order Status",
  runsheetCreationDate = "Runsheet Creation Date",
  runsheetUid = "Runsheet UID",
  runsheetStatus = "Runsheet Status",
  taskUidPickup = "Task UID Pickup",
  dateReceptionAtHub = "Date Reception At Hub",
  receiverAtHub = "Parcel Receiver At Hub",
  receiverPhoneNumberAtHub = "Parcel Receiver Phone Number At Hub",
  lastReason = "Parcel Last Reason",
  description = "Parcel Description",
  lastHandedoverDateTime = "Parcel Last HandedOver Date Time",
  pickupAssignement = "Parcel Pickup Assignement",
  tag = "Tag",
  platform = "Platform"
}

export enum ExportType {
  MSG = "MSG",
  NT = "NT",
  MAD = "MAD",
  TR = "TR"
}

registerEnumType(ExportType, { name: "ExportType" });
