import { AnalyticsData } from "../schema";

export const parcels: AnalyticsData[] = [
  {
    "Parcel UID": "PP-O9972822-2693",
    "Parcel Aging": 121,
    "Parcel Delivery Date": " ",
    "Parcel Return Date": " ",
    "Parcel Last OPS Update": "2022-09-26",
    "Parcel Reconcil Date": " ",
    "Parcel Reconcil Agent": " ",
    "Last Update Papser Date": "2022-09-26",
    "Last Update Papser": "Mouhamed Aly SIDIBE",
    "Last Update Papser Phone": "+221778618313",
    "Parcel Collection By Cashier Date": " ",
    "Parcel Last OPS Update Name": "Admin Admin",
    "Parcel Last OPS Update Phone": " ",
    Slots: " ",
    "Parcel Size": "XXL",
    "Parcel Attemps": 0,
    "Parcel Attemps Real": 1,
    "Parcel Creation Date": "2022-09-26",
    "Scheduled Date": " ",
    "Parcel Pickup Date": " ",
    "Parcel Amount To Collect": 0,
    "Parcel Status": "TO_RETURN",
    "Parcel Last Reason": "Several unsuccessful attempts",
    "Parcel Description": "sps",
    "Parcel Last HandedOver Date Time": null,
    "Parcel Pickup Assignement": " ",
    Tag: "DEFAULT",
    Platform: "Paps Ops",
    Client: "TESTAPI",
    "Client Phone": "+221770001211",
    "Client Address": "100f Bd de St Louis, Dakar, Senegal",
    "Client City": "Fann-Point E-Amitié",
    "Client Country": "Senegal",
    "Client Storage Option": "N/A",
    Receiver: " ",
    "Receiver Phone": " ",
    "Receiver Address": " ",
    "Receiver City": " ",
    "Receiver Country": " ",
    "Parcel Last Driver Name": "Mouhamed Aly SIDIBE",
    "Parcel Last Driver Phone": "+221778618313",
    "Parcel Last Driver UID": "PP-D-000001",
    "Vehicle Type": " ",
    "Parcel Last Conveyor Name": " ",
    "Parcel Last Conveyor Phone": " ",
    "Parcel Last Conveyor UID": " ",
    "Parcel Last Partner": "SIDIBEBANG",
    "Order UID": "PP-O4006026",
    "Number Of Parcel In Order": 1,
    "Order Creation Date": "2022-09-26",
    "Order Size": " ",
    "Order Amount Collect": 0,
    "Order Status": "TO_RETURN",
    "Runsheet Creation Date": "N/A",
    "Runsheet UID": " ",
    "Runsheet Status": " ",
    "Task UID Pickup": " ",
    "Date Reception At Hub": " ",
    "Parcel Receiver Phone Number At Hub": " ",
    "Parcel Receiver At Hub": "N/A"
  }
];
